name: iForm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build for iOS 
      run: xcodebuild build-for-testing -scheme "iForm" -destination "name=iPhone 11" | xcpretty;

    - name: Run iOS tests 
      run: xcodebuild test-without-building -scheme "iForm" -destination "name=iPhone 11" | xcpretty;
